### ISSUE TITLE
Invalid CMD command

### ISSUE THREAD

**Issue by Rungerr** [xCloudzx/discordbotdash#2]
Hello!
Against me!
I have an other problem, there is a problem with CMD commands.
Look:
![image](https://user-images.githubusercontent.com/66308401/102988534-51dc8100-4514-11eb-9ddc-7a3c056cc5b3.png)
I don't know how to use cmd commands :/
thx

**Comment by xCloudzx** [comment]
Hello, thank you for opening an issue! I do not understand what a cmd command is though, and it would be very helpful if you provided steps to reproduce this error: 
What is `[global_opts]`? 
Where is this error being shown? The web console or the actual console where you run the code? 

Once again, thank you.

**Comment by Rungerr** [comment]
Hello!
The thing is I don't really know how to deploye the bot and the dashboard.
If you can explain me how this module work, and how can I use your module I will be very grateful.
Thanks for you answer!

**Comment by xCloudzx** [comment]
There is currently a working example in the README. You can just import the module's open function and call it in your `on_ready` event before running the bot and pass in the bot as an argument. 

The dashboard allows you to enable and disable commands and cogs by checking and unchecking them (and pressing Update). The console outputs these events, so you can keep a log of what has happened.

**Comment by Rungerr** [comment]
Thank you very much! And GG for this amazing module! I really love it!

**Comment by xCloudzx** [comment]
Thank you! Let me know if there's anything you would like me to add to it. Also has the problem been fixed? If so I can close this issue.

**Comment by Rungerr** [comment]
Yes the problem is off. The only question is : could we use this module to create a dashboard, connect this dashboard to a domain, and create a bot dashboard accessible by all the bot users ?

**Comment by xCloudzx** [comment]
I had originally intended for this to be used for testing purposes. However, that should be possible, but anyone with the URL will be able to turn commands and cogs on and off.

**Comment by Rungerr** [comment]
ok I see, thanks! Mabye if you add a button "connect with discord" it will be possible?

**Comment by xCloudzx** [comment]
That might be possible. I'll have to look into it.

**Comment by Rungerr** [comment]
Ok thanks! Last question and I'll leave you alone :) Can we change the code of cogs.html and commands.html and if I chnage it, can we see the changes that we did? 
(i am not very clear, hope you understood)

**Comment by xCloudzx** [comment]
Yes, you can. You will have to edit the module, so the changes will not remain between updates. The module folder can be found with [this](https://stackoverflow.com/questions/2927993/where-are-the-python-modules-stored/2928020) in a folder called discordbotdash. The html files will be in the app/templates directory and the css for them will be in the app/static/css directory.

**Comment by Rungerr** [comment]
Thanks you very much!
