### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by myusernameDiscord** [xCloudzx/discordbotdash#3]
Hi is it possible to change the port

**Comment by xCloudzx** [comment]
It is now :). I've added the option to the `openDash` call: `dbd.openDash(bot, port=5000)` (see comment in README example).

**Comment by myusernameDiscord** [comment]
Thank you very much

**Comment by myusernameDiscord** [comment]
![3D12832F-B492-4216-BC9B-C7DFBFC00A5C](https://user-images.githubusercontent.com/62823057/111054707-b7605e00-84c2-11eb-9984-04e24de8fd17.jpeg)
so I changed it to say dbd.openDash(bot, port=1101) but now I get an error

**Comment by xCloudzx** [comment]
Have you updated the package: `pip install --upgrade discordbotdash`.

**Comment by myusernameDiscord** [comment]
How to enable debug mode

**Comment by xCloudzx** [comment]
For the flask server? Why would you want debug mode on that?

**Comment by myusernameDiscord** [comment]
It see why it can’t connect I get no error in console but I can’t access the web page

**Comment by xCloudzx** [comment]
What's the http error and what URL are you trying to connect to?

**Comment by myusernameDiscord** [comment]
http://n5.danbot.host:1101
Safari can’t open the page because the network connection was lost

**Comment by xCloudzx** [comment]
Not sure what the problem is, but this really isn't meant to be used in production. I initially created for local development.
